export const categories = [
  {
    id: 'aretes',
    name: 'Aretes',
    image: '/catalogo/categoria-aretes.svg',
    description: 'Piezas livianas, coloridas y con mini detalles hechos a mano.'
  },
  {
    id: 'collares',
    name: 'Collares',
    image: '/catalogo/categoria-collares.svg',
    description: 'Dijes y piedras coloridas con personalidad artesanal.'
  },
  {
    id: 'llaveros',
    name: 'Llaveros',
    image: '/catalogo/categoria-llaveros.svg',
    description: 'Compañeritos para bolsos, llaves y regalos con personalidad.'
  },
  {
    id: 'cabello',
    name: 'Cabello',
    image: '/catalogo/categoria-cabello.svg',
    description: 'Ganchitos, pinzas y detalles para peinados con cuento propio.'
  },
  {
    id: 'mascotas',
    name: 'Accesorios para mascotas',
    image: '/catalogo/categoria-mascotas.svg',
    description: 'Collares, plaquitas y charms pensados para consentirlos.'
  },
  {
    id: 'personalizados',
    name: 'Personajes personalizados',
    image: '/catalogo/categoria-personajes.svg',
    description: 'Mini versiones de personas, mascotas o personajes favoritos.'
  },
  {
    id: 'regalos',
    name: 'Regalos',
    image: '/catalogo/categoria-regalos.svg',
    description: 'Packs armados con cariño para fechas especiales.'
  }
];

export const products = [
  {
    id: 'aretes-orquideas-rosadas',
    name: 'Aretes orquídeas rosadas',
    price: 50000,
    category: 'aretes',
    type: 'Aretes',
    status: 'disponible',
    isFeatured: true,
    isNew: true,
    image: '/catalogo/aretes-orquideas-rosadas.svg',
    gallery: ['/catalogo/aretes-orquideas-rosadas.svg', '/catalogo/detalle-sapitos.svg'],
    description: 'Aretes florales del catálogo Sapitos con acabado delicado y presencia protagonista.',
    materials: 'Porcelanicron y acero inoxidable.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Color de flor', 'Tipo de gancho', 'Empaque para regalo']
  },
  {
    id: 'aretes-snoopy-fresita',
    name: 'Aretes Snoopy fresita',
    price: 40000,
    category: 'aretes',
    type: 'Aretes',
    status: 'disponible',
    isFeatured: true,
    isNew: true,
    image: '/catalogo/aretes-snoopy-fresita.svg',
    gallery: ['/catalogo/aretes-snoopy-fresita.svg', '/catalogo/detalle-corazones.svg'],
    description: 'Aretes juguetones inspirados en personaje y fresitas, pensados para looks tiernos.',
    materials: 'Porcelanicron y acero inoxidable.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Color de fresa', 'Tamaño', 'Empaque para regalo']
  },
  {
    id: 'aretes-lulos',
    name: 'Aretes lulos',
    price: 35000,
    category: 'aretes',
    type: 'Aretes',
    status: 'disponible',
    isFeatured: false,
    isNew: true,
    image: '/catalogo/aretes-lulos.svg',
    gallery: ['/catalogo/aretes-lulos.svg', '/catalogo/detalle-estrellas.svg'],
    description: 'Mini frutas coloridas con vibra tropical y acabado artesanal.',
    materials: 'Porcelanicron y acero inoxidable.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Fruta favorita', 'Color', 'Tipo de cierre']
  },
  {
    id: 'aretes-sapitos-catalogo',
    name: 'Aretes sapitos',
    price: 26000,
    category: 'aretes',
    type: 'Aretes',
    status: 'disponible',
    isFeatured: true,
    isNew: false,
    image: '/catalogo/aretes-sapitos.svg',
    gallery: ['/catalogo/aretes-sapitos.svg', '/catalogo/detalle-sapitos.svg'],
    description: 'Aretes de sapitos del catálogo real, ligeros, cute y muy de la casa.',
    materials: 'Porcelanicron, acrílico y acero inoxidable.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Expresión', 'Color del sapito', 'Brillo']
  },
  {
    id: 'collar-usahana',
    name: 'Collar Usahana',
    price: 48000,
    category: 'collares',
    type: 'Collar',
    status: 'disponible',
    isFeatured: true,
    isNew: true,
    image: '/catalogo/collar-usahana.svg',
    gallery: ['/catalogo/collar-usahana.svg', '/catalogo/detalle-collares.svg'],
    description: 'Collar con dije protagonista y mezcla de piedras en una paleta dulce.',
    materials: 'Porcelanicron, piedras de acrílico, murano y acero inoxidable.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Largo de collar', 'Color base', 'Inicial opcional']
  },
  {
    id: 'collar-arandano',
    name: 'Collar Arándano',
    price: 45000,
    category: 'collares',
    type: 'Collar',
    status: 'disponible',
    isFeatured: false,
    isNew: true,
    image: '/catalogo/collar-arandano.svg',
    gallery: ['/catalogo/collar-arandano.svg', '/catalogo/detalle-collares.svg'],
    description: 'Collar frutal con piedras, murano y un dije artesanal lleno de color.',
    materials: 'Porcelanicron, piedras de acrílico, murano y acero inoxidable.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Paleta de piedras', 'Largo', 'Dije adicional']
  },
  {
    id: 'llavero-mariquita',
    name: 'Llavero mariquita',
    price: 25000,
    category: 'llaveros',
    type: 'Llavero',
    status: 'disponible',
    isFeatured: true,
    isNew: false,
    image: '/catalogo/llavero-mariquita.svg',
    gallery: ['/catalogo/llavero-mariquita.svg', '/catalogo/detalle-estrellas.svg'],
    description: 'Llavero de mariquita con detalles brillantes y herraje resistente.',
    materials: 'Porcelanicron, perla de vidrio, acrílico y aleación de metal.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Inicial', 'Color de herraje', 'Charm extra']
  },
  {
    id: 'llavero-sapito-culoncito',
    name: 'Llavero sapito culoncito',
    price: 18000,
    category: 'llaveros',
    type: 'Llavero',
    status: 'disponible',
    isFeatured: true,
    isNew: false,
    image: '/catalogo/llavero-sapito-culoncito.svg',
    gallery: ['/catalogo/llavero-sapito-culoncito.svg', '/catalogo/detalle-sapitos.svg'],
    description: 'Sapito mini para llevar en llaves o bolso, con humor y mucha ternura.',
    materials: 'Porcelanicron, murano, botones y aleación de metal.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Color del sapito', 'Inicial', 'Charm extra']
  },
  {
    id: 'ganchitos-hongos-3d',
    name: 'Ganchitos hongos 3D',
    price: 16000,
    category: 'cabello',
    type: 'Cabello',
    status: 'disponible',
    isFeatured: false,
    isNew: false,
    image: '/catalogo/ganchitos-hongos-3d.svg',
    gallery: ['/catalogo/ganchitos-hongos-3d.svg', '/catalogo/detalle-hongos.svg'],
    description: 'Par de ganchitos con honguitos 3D para peinados juguetones.',
    materials: 'Porcelanicron y aleación de metal.',
    productionTime: 'Entrega inmediata según disponibilidad',
    customization: ['Color del hongo', 'Par o unidad', 'Tamaño']
  },
  {
    id: 'aretes-sapito-feliz',
    name: 'Aretes Sapito Feliz',
    price: 28000,
    category: 'aretes',
    type: 'Aretes',
    status: 'disponible',
    isFeatured: true,
    isNew: true,
    image: '/catalogo/aretes-sapito-feliz.svg',
    gallery: ['/catalogo/aretes-sapito-feliz.svg', '/catalogo/detalle-sapitos.svg'],
    description: 'Aretes artesanales con caritas de sapito, brillo suave y acabado tipo sticker coleccionable.',
    materials: 'Arcilla polimérica, acero inoxidable, barniz protector y detalles pintados a mano.',
    productionTime: '2 a 4 días hábiles',
    customization: ['Color del sapito', 'Expresión', 'Tipo de gancho', 'Empaque para regalo']
  },
  {
    id: 'llavero-ranita-estrella',
    name: 'Llavero Ranita Estrella',
    price: 32000,
    category: 'llaveros',
    type: 'Llavero',
    status: 'por encargo',
    isFeatured: true,
    isNew: true,
    image: '/catalogo/llavero-ranita-estrella.svg',
    gallery: ['/catalogo/llavero-ranita-estrella.svg', '/catalogo/detalle-estrellas.svg'],
    description: 'Llavero con ranita, estrellas colgantes y mezcla de colores dulces para cargar buena vibra.',
    materials: 'Acrílico, resina, herraje metálico, dijes y pintura manual.',
    productionTime: '4 a 6 días hábiles',
    customization: ['Inicial', 'Color de estrella', 'Nombre corto', 'Charm adicional']
  },
  {
    id: 'collar-mascota-personalizado',
    name: 'Collar para mascota personalizado',
    price: 45000,
    category: 'mascotas',
    type: 'Mascotas',
    status: 'disponible',
    isFeatured: false,
    isNew: true,
    image: '/catalogo/collar-mascota-personalizado.svg',
    gallery: ['/catalogo/collar-mascota-personalizado.svg', '/catalogo/detalle-mascotas.svg'],
    description: 'Collar ajustable con plaquita personalizada, ideal para mascotas con estilo propio.',
    materials: 'Cinta resistente, broche plástico, argolla metálica y plaquita artesanal.',
    productionTime: '3 a 5 días hábiles',
    customization: ['Nombre de mascota', 'Color de cinta', 'Figura de plaquita', 'Teléfono opcional']
  },
  {
    id: 'mini-personaje-personalizado',
    name: 'Mini personaje personalizado',
    price: 60000,
    category: 'personalizados',
    type: 'Personaje',
    status: 'por encargo',
    isFeatured: true,
    isNew: false,
    image: '/catalogo/mini-personaje-personalizado.svg',
    gallery: ['/catalogo/mini-personaje-personalizado.svg', '/catalogo/detalle-personaje.svg'],
    description: 'Mini personaje hecho a partir de una referencia: persona, mascota, avatar o idea especial.',
    materials: 'Arcilla polimérica, pintura acrílica, barniz protector y base opcional.',
    productionTime: '7 a 12 días hábiles',
    customization: ['Ropa', 'Peinado', 'Accesorios', 'Base con nombre']
  },
  {
    id: 'pack-regalo-sapitos',
    name: 'Pack regalo Sapitos',
    price: 72000,
    category: 'regalos',
    type: 'Pack',
    status: 'disponible',
    isFeatured: true,
    isNew: false,
    image: '/catalogo/pack-regalo-sapitos.svg',
    gallery: ['/catalogo/pack-regalo-sapitos.svg', '/catalogo/detalle-regalos.svg'],
    description: 'Caja de regalo con accesorios sorpresa, empaque bonito y espacio para mensaje personalizado.',
    materials: 'Mix de accesorios artesanales, stickers, papel decorativo y caja rígida.',
    productionTime: '2 a 3 días hábiles',
    customization: ['Paleta de color', 'Mensaje', 'Tipo de accesorio', 'Tema del regalo']
  },
  {
    id: 'aretes-corazon-artesanal',
    name: 'Aretes corazón artesanal',
    price: 26000,
    category: 'aretes',
    type: 'Aretes',
    status: 'agotado',
    isFeatured: false,
    isNew: false,
    image: '/catalogo/aretes-corazon-artesanal.svg',
    gallery: ['/catalogo/aretes-corazon-artesanal.svg', '/catalogo/detalle-corazones.svg'],
    description: 'Aretes de corazón con acabado brillante y textura handmade, perfectos para looks tiernos.',
    materials: 'Arcilla polimérica, acero inoxidable, pigmentos y barniz.',
    productionTime: 'Próximo drop por anunciar',
    customization: ['Color', 'Brillo', 'Tamaño mini o mediano']
  }
];

export const formatCOP = (value) =>
  new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency: 'COP',
    maximumFractionDigits: 0
  }).format(value);
